### ISSUE TITLE
Callbacks are not called in real code

### ISSUE THREAD

**Issue by securigy** [elstepherino/InvernessPark.Utilities.NMEA#1] opened 2022-09-24 00:54 UTC
"The above code will invoke the appropriate callbacks each time a NMEA sentence is received."
This is not happening - it only happens in test code but not when I implement the example...

**Comment by elstepherino** [comment] 2022-09-24 09:01
Can you please provide the data stream sample you are using? 

I've updated the demo code in the readme file.  It uses a sample file and reads NMEA text 32 bytes at a time.  

The data was generated from https://www.nmeagen.org.

**Comment by securigy** [comment] 2022-09-24 17:52
What I did is this: (the handler and receiver are members of the class...

        //private void InitializeNmeaParser()
        //{
        //    using (Log.VerboseCall())
        //    {
        //        // Create an object to handle parsed NMEA messages
        //        mNmeaHandler = new DefaultNmeaHandler();
        //        mNmeaHandler.LogNmeaMessage += str => {
        //            Log.VerboseFormat("New NMEA Message: {0}", str);
        //        };

        //        // Create the NMEA receiver
        //        mNmeaReceiver = new NmeaReceiver(mNmeaHandler);

        //        // Attach handler for NMEA messages that fail NMEA checksum verification
        //        mNmeaReceiver.NmeaMessageFailedChecksum += NmeaReceiver_NmeaMessageFailedChecksum;

        //        // Attach handler for NMEA messages that contain invalid syntax
        //        mNmeaReceiver.NmeaMessageDropped += (bytes, index, count, reason) =>
        //        {
        //            Log.VerboseFormat("Bad Syntax: {0}; reason: {1}",
        //                Encoding.ASCII.GetString(bytes.Skip(index).Take(count).ToArray()),
        //                reason);
        //        };

        //        // Attach handler for NMEA messages that are ignored (unsupported)
        //        mNmeaReceiver.NmeaMessageIgnored += (bytes, index, count) =>
        //        {
        //            Log.VerboseFormat("Ignored: {0}",
        //                Encoding.ASCII.GetString(bytes.Skip(index).Take(count).ToArray()));
        //        };

        //        // Byte receiving logic...
        //        bool keepReceiving = true;
        //        while (keepReceiving)
        //        {
        //            string sentence = "$GPRMC,123519.00,A,4807.038,N,01131.000,E,,,230394,,,A*6A";
        //            // !!! temp - receive some bytes from socket, file, whatever... 
        //            byte[] bytesReceived = Encoding.ASCII.GetBytes(sentence);

        //            BooleanPlaceholder _rmcReceived = new BooleanPlaceholder();
        //            _rmcReceived.set_state(false);

        //            // ... Feed the bytes into the NMEA receiver
        //            mNmeaReceiver.Receive(bytesReceived);
        //            keepReceiving = false;
        //        }

        //    }
        //}

**Comment by elstepherino** [comment] 2022-09-24 17:58
Ah OK, I see what the issue is:  the parser will wait until it encounters the "end of line" delimiter.   So if you just add "\n", or "\r\n", you should see the intended behavior.  The parser follows the spec quite closely.  The spec says CR LF terminates the message, but LF will also work.

*** One thing to note though is that the sample NMEA message you provided fails on the checksum test.  Before I start debugging on my end, can you verify that this isn't a mistake with the specific NMEA sentence you are using?

Here are samples I used - and that pass the checksum - from the 3rd-party site www.nmeagen.org:

$GPGGA,093741.805,5231.694,N,01323.983,E,1,12,1.0,0.0,M,0.0,M,,*64
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,093741.805,A,5231.694,N,01323.983,E,5662.9,072.5,240922,000.0,W*41
$GPGGA,093742.805,5232.414,N,01326.280,E,1,12,1.0,0.0,M,0.0,M,,*63
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,093742.805,A,5232.414,N,01326.280,E,050.5,073.0,240922,000.0,W*7C
$GPGGA,093743.805,5232.421,N,01326.300,E,1,12,1.0,0.0,M,0.0,M,,*6D
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,093743.805,A,5232.421,N,01326.300,E,050.5,000.0,240922,000.0,W*76
$GPGGA,093744.805,5232.421,N,01326.300,E,1,12,1.0,0.0,M,0.0,M,,*6A
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,093744.805,A,5232.421,N,01326.300,E,000.0,000.0,240922,000.0,W*71

**Comment by securigy** [comment] 2022-09-25 18:35
Oh, I see, forgetting the \r\n ...
I do not recall where I got this message - copied from some site...it is not guaranteed to be valid.

**Comment by elstepherino** [comment] 2022-09-26 13:05
Issue resolved with a clarification on use case.

**Closed as completed** 2022-09-26 13:04 UTC
